# Generated by Django 5.1.7 on 2025-04-23 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_desc',
            field=models.CharField(default='No description', max_length=200),
        ),
        migrations.AddField(
            model_name='item',
            name='item_name',
            field=models.CharField(default='Dummy', max_length=200),
        ),
    ]
