# Generated by Django 5.1.7 on 2025-05-22 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_item_item_desc_item_item_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://orders.goodthymes.ca/assets/img/goodthymes/default-menu-image-placeholder.png', max_length=200),
        ),
    ]
